### ISSUE TITLE
Error during placement

### ISSUE THREAD

**Issue by mxmxchere** [23technologies/gardener-extension-provider-hcloud#11]
Sometimes the creation of a machine fails with the error "error during placement". Perhaps this is caused by the placement groups that causes fewer options for the scheduler to place vms on their hypervisors

**Comment by mxmxchere** [comment]
this is the log output:

`task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--23ke-ci--23ke-run-cef1/23ke-run-cef1 to become ready: error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'machine(s) failed: 1 error occurred: "shoot--23ke-ci--23ke-run-cef1-worker-cx41-fsn1-dc14-c6cb8-657z6", "shoot--23ke-ci--23ke-run-cef1-worker-cx41-fsn1-dc14-c6cb8-g9pgj": Cloud provider message - machine codes error: code = [Unavailable] message = [error during placement (resource_unavailable)]'`

**Comment by NotTheEvilOne** [comment]
Reopen issue due to changes being likely required for `gardener-extension-provider-hcloud` as well.

**Comment by mxmxchere** [comment]
The shoot is scaled to at most 4 servers. If the placement-group feature causes problems then it should be optional
