### ISSUE TITLE
Evaluate hcloud-cloud-controller-manager image

### ISSUE THREAD

**Issue by fynluk** [23technologies/gardener-extension-provider-hcloud#23]
**How to categorize this issue?**

/area performance
/area quality
/area robustness
/kind bug
/kind enhancement
/kind question

**What happened**:
Right now we are using our own image for the `hcloud-cloud-controller-manager`. We should consider if this is still necessary. If not we should use the upstream image again.
https://github.com/23technologies/hcloud-cloud-controller-manager/commit/ef1d76fdf44077cbeff256731eea3a1710eb8d0b would fix a major problem.

**Comment by JensAc** [comment]
This commit https://github.com/23technologies/hcloud-cloud-controller-manager/commit/3c8259602508ce74528a8aedf02fc4ab03338d2d
introduces some changes on our side. We should check, whether these are still required.
